# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Sonny
tagline:          'Creative Engineering'
description:      'Petroleum & Software engineering'
baseurl:          "/"
url: 			  "http://sonny-qa.github.io"
disqus: 		  "sonny-qa"

author:
  name:           'Mark Otto'


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sonny-qa

